api = "0.10"

[buildpack]
id = "neeto-deploy/awscli"
version = "0.0.6"
name = "NeetoDeploy AWS CLI Buildpack"
description = "A Cloud Native Buildpack that installs AWS CLI for AWS operations"

[metadata]
include-files = [
  "bin/build",
  "bin/detect",
  "bin/release",
  "profile/awscli.sh",
  "buildpack.toml",
]

[[stacks]]
id = "*"

[[targets]]
os = "linux"
arch = "amd64"

[[targets]]
os = "linux"
arch = "arm64"
